data:
  mu: 0
  sigma: 5
  dist_mu: 10
  dist_sigma: 10
  angle_mu: 0
  angle_sigma: 40

acquisition:
  option: 3
  q: 1
  num_restarts: 10
  raw_samples: 40 # initialization heuristic
  bounds: 120
  beta: 0.2
  best_f: 0.1

train:
  num_epoch: 10
  num_samples: 1000

np:
  num_context: 10
  hidden_dim: 10
  decoder_dim: 15
  z_samples: 20

MOM4:
  parttype: R1005
  xvar_pre: PRE_X
  yvar_pre: PRE_Y
  xvar_post: POST_X
  yvar_post: POST_Y
