toy:
  mu: 0
  sigma: 120

acquisition:        # by default, it uses multi-start optimization
  option: 1         # acquisition function type 
  q: 1              # smallest number of candidates to be considered jointly
  num_restarts: 10  # number of starting points for multi-start acquisition function
  raw_samples: 40   # number of samples for initialization
  bounds: 120       # 2xd tensor of lower and upper bounds for each column of X
  beta: 0.2
  best_f: 0.1

train:
  num_iter: 50
  num_epoch: 100
  num_samples: 1000

np:
  input_dim: 3
  num_context: 10
  hidden_dim: 128
  decoder_dim: 15
  z_samples: 20

MOM4:
  parttype: R1005 # [R0402, R0603, R1005, all]
  input_var:
    - PRE_L
    - PRE_W
    # - PRE_A
    # - SPI_L
    # - SPI_W
    # - SPI_VOLUME_DIFF
  output_var:
    - POST_L
    - POST_W
